import { motion } from "framer-motion";
import { ShieldCheck, Sparkles, MessageSquare } from "lucide-react"; // icons

export default function SupportModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-[#000000c7] z-50">
      <motion.div
        initial={{ opacity: 0, scale: 0.85 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.85 }}
        className="bg-white rounded-xl shadow-lg w-full max-w-md overflow-hidden"
      >
        {/* Top Icon */}
        <div className="flex justify-center mt-6">
          <div className="bg-green-100 p-4 rounded-full">
            <MessageSquare className="text-green-600 h-8 w-8" />
          </div>
        </div>

        {/* Title */}
        <h2 className="text-lg font-semibold text-center mt-4 mb-2">
          Get help from official ChatSphere Support
        </h2>

        {/* Feature List */}
        <div className="px-6 space-y-2 text-gray-700 text-sm">
          <p className="flex items-center gap-2">
            <ShieldCheck className="h-4 w-4 text-gray-600" />
            Secure chat with ChatSphere
          </p>
          <p className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-gray-600" />
            Answers may be AI generated
          </p>
          <p className="flex items-center gap-2">
            <MessageSquare className="h-4 w-4 text-gray-600" />
            Help us improve with feedback
          </p>
        </div>

        {/* Small Note */}
        <p className="text-xs text-gray-500 mt-4 px-6 leading-relaxed">
          Some answers are generated by AI using a secure technology from Meta. ChatSphere uses your messages with ChatSphere Support to provide you with relevant answers. Your personal messages and calls remain end-to-end encrypted.
        </p>

        {/* Footer Buttons */}
        <div className="flex justify-end items-center gap-3 px-6 py-4 border-t">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded border text-gray-700 bg-gray-100 hover:bg-gray-200"
          >
            Cancel
          </button>
          <button className="px-4 py-2 rounded bg-green-600 text-white hover:bg-green-700">
            Start chat
          </button>
        </div>
      </motion.div>
    </div>
  );
}
